apiVersion: v1
kind: PersistentVolume
metadata:
  name:  pv1
  namespace: nginx-service
spec:
  capacity: 
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /root/share
    server: 192.168.12.129
