apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 8080  
    nodePort: 32000
    #这个资源(svc)开放的端口
    targetPort: 80
