apiVersion: v1
kind: Service
metadata:
  labels:
    app: kube-state-metrics
    k8s-app: kube-state-metrics
  name: kube-state-metrics
  namespace: monitoring
spec:
  ports:
  - name: http-metrics
    port: 8080
    protocol: TCP
    targetPort: metrics
    nodePort: 30001
  selector:
    app: kube-state-metrics
  sessionAffinity: None
  #type: ClusterIP
  type: NodePort

