apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv11
  namespace: monitoring
spec:
  storageClassName: prometheus-data
  capacity: 
    storage: 5Gi  
  accessModes: 
    - ReadWriteOnce  
  persistentVolumeReclaimPolicy: Recycle 
  nfs:
    path: /root/data
    server: 192.168.12.129

#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
  #name: pvc11
  #namespace: monitoring 
#spec:
  #accessModes:
    #- ReadWriteOnce 
  #resources:
    #requests:
      #storage: 5Gi 
  #storageClassName: prometheus-data
